### ISSUE TITLE
PWP Capstone Feedback

### ISSUE THREAD

**Issue by mackenzieyoung** [costanikou/pwp-capstones#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Great job, your code runs without any errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Good, your code produces the suite of functions and classes required of it and calls them in an appropriate order.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Nice job, your code is separated into distinct classes and functions, each which are invoked for their own purposes.
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Good, your code uses Python features appropriately.

### Criteria 5: Produces Accurate Output
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Good job, your code output is properly formatted and accurate.
 
### Overall Score: 20/20
Excellent job! I especially like how you used simple test cases to test your functions. That way, you can know for sure if your function actually works, because you know what the output should be. I don't see this done often enough, but it's one of the best ways to test and debug your code.

**Comment by costanikou** [comment]
thanks!
